# Development Dockerfile for the project
FROM --platform=linux/amd64 node:18-alpine

WORKDIR /app

COPY prisma ./
COPY package.json pnpm-lock.yaml ./

RUN yarn global add pnpm && pnpm install

COPY . .

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

USER nextjs

EXPOSE 3000
ENV PORT 3000

CMD ["pnpm", "run", "dev"]